# Generated by Django 5.0.9 on 2024-10-21 09:32
import uuid

from django.db import migrations


def generate_uuid(apps, schema_editor):
    model = apps.get_model("users", "User")
    for row in model.objects.iterator():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_uid'),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
