# Generated by Django 5.0.9 on 2024-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_characteristicvisibility_game_delete_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='orientation',
            field=models.CharField(blank=True, choices=[('homosexual', 'Гомосексуален'), ('asexual', 'Асексуален'), ('heterosexual', 'Гетеросексуален')], null=True, verbose_name='ориентация'),
        ),
    ]
