# Generated by Django 5.0.9 on 2024-10-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_bunker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('key', models.SlugField(verbose_name='ключ карты')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='описание')),
                ('target', models.CharField(blank=True, choices=[('all', 'Все персонажи'), ('myself', 'На себя'), ('another_personage', 'Другой персонаж'), ('game', 'Игра')], max_length=30, null=True, verbose_name='цель')),
            ],
            options={
                'verbose_name': 'карта действия',
                'verbose_name_plural': 'карты действия',
            },
        ),
        migrations.CreateModel(
            name='ActionCardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='использована')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.actioncard', verbose_name='карта')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_cards', to='game.game', verbose_name='игра')),
                ('personage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_cards', to='game.personage', verbose_name='персонаж')),
            ],
            options={
                'unique_together': {('card', 'personage', 'game')},
            },
        ),
    ]
