# Generated by Django 5.0.9 on 2024-10-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_actioncard_actioncardusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='degree',
        ),
        migrations.AddField(
            model_name='disease',
            name='degree_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='процент болезни'),
        ),
        migrations.AlterField(
            model_name='baggage',
            name='status',
            field=models.CharField(blank=True, choices=[('intact', 'Целый'), ('damaged', 'Поврежденный')], max_length=50, null=True, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='is_curable',
            field=models.BooleanField(blank=True, null=True, verbose_name='можно вылечить'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='experience',
            field=models.CharField(blank=True, choices=[('novice', 'Новичок'), ('amateur', 'Любитель'), ('experienced', 'Опытный'), ('professional', 'Профессионал'), ('master', 'Мастер')], null=True, verbose_name='опыт хобби'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.additionalinfo', verbose_name='доп, информация'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='baggage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.baggage', verbose_name='багаж'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character', verbose_name='характер'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.disease', verbose_name='болезнь'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hobby', verbose_name='хобби'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='phobia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.phobia', verbose_name='фобия'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.profession', verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='phobia',
            name='stage',
            field=models.CharField(blank=True, choices=[('none', 'Отсутствует'), ('mild', 'Легкая'), ('moderate', 'Средняя'), ('severe', 'Серьезная'), ('panic', 'Паническая')], max_length=120, null=True, verbose_name='стадия'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='experience',
            field=models.CharField(blank=True, choices=[('novice', 'Новичок'), ('amateur', 'Любитель'), ('experienced', 'Опытный'), ('professional', 'Профессионал'), ('master', 'Мастер')], null=True, verbose_name='опыт работы'),
        ),
    ]
