# Generated by Django 5.0.9 on 2024-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20241021_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='baggage',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирована'),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирована'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирована'),
        ),
        migrations.AddField(
            model_name='phobia',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирована'),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирована'),
        ),
    ]
