# Generated by Django 5.0.9 on 2024-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_baggage_is_generated_disease_is_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирован'),
        ),
        migrations.AddField(
            model_name='profession',
            name='additional_skill',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='дополнительное умение'),
        ),
        migrations.AlterField(
            model_name='bunker',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='bunker',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='game.bunkerroom', verbose_name='комнаты'),
        ),
    ]
