# Generated by Django 5.0.9 on 2024-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_bunker_is_generated_profession_additional_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastrophe',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='сгенерирован'),
        ),
        migrations.AddField(
            model_name='catastrophe',
            name='percent_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='процент выжившего населения'),
        ),
        migrations.AlterField(
            model_name='catastrophe',
            name='description',
            field=models.CharField(max_length=500, verbose_name='описание'),
        ),
    ]
