# Generated by Django 5.0.9 on 2024-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_catastrophe_is_generated_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actioncardusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='game_duration_type',
            field=models.CharField(blank=True, choices=[('short', 'Короткая'), ('medium', 'Средняя'), ('long', ' Длинная')], default='medium', verbose_name='длительность игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='num_places',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='мест в бункере'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_in_bunker',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='продолжительность в бункере'),
        ),
        migrations.AlterField(
            model_name='phobia',
            name='stage',
            field=models.CharField(blank=True, choices=[('initial', 'Начальная'), ('mild', 'Легкая'), ('moderate', 'Средняя'), ('severe', 'Серьезная'), ('panic', 'Паническая')], default='', max_length=120, verbose_name='стадия'),
        ),
        migrations.AddConstraint(
            model_name='actioncardusage',
            constraint=models.UniqueConstraint(fields=('personage', 'game', 'card'), name='unique_personage_game_action_card'),
        ),
        migrations.AddConstraint(
            model_name='actioncardusage',
            constraint=models.UniqueConstraint(fields=('personage', 'card'), name='unique_personage_action_card'),
        ),
    ]
