# Generated by Django 5.0.9 on 2024-10-30 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_actioncardusage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='начато в')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='game.game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'голосование',
                'verbose_name_plural': 'голосования',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_vote', to='game.personage', verbose_name='кандидат')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_vote', to='game.personage', verbose_name='голосующий')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.voting', verbose_name='голосование')),
            ],
            options={
                'verbose_name': 'голос',
                'verbose_name_plural': 'голоса',
            },
        ),
    ]
