# Generated by Django 5.0.9 on 2024-11-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_voting_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioncardusage',
            options={'verbose_name': 'использование карты действия', 'verbose_name_plural': 'использования карт действий'},
        ),
        migrations.RemoveConstraint(
            model_name='actioncardusage',
            name='unique_personage_game_action_card',
        ),
        migrations.RemoveConstraint(
            model_name='actioncardusage',
            name='unique_personage_action_card',
        ),
    ]
